export const icons = {
  'timer-icon': 'timer-icon.svg',
  'connector-icon': 'connector-icon.svg',
  'custom-note-icon': 'custom-note-icon.svg',
  'end-icon': 'end-icon.svg',
  'gateway-icon': 'gateway-icon.svg',
  'loop-icon': 'loop-icon.svg',
  'message-icon': 'message-icon.svg',
  'parallel-icon': 'parallel-icon.svg',
  'script-icon': 'script-icon.svg',
  'service-call-icon': 'service-call-icon.svg',
  'signal-listen-icon': 'signal-listen-icon.svg',
  'signal-send-icon': 'signal-send-icon.svg',
  'start-icon': 'start-icon.svg',
  'sub-process-icon': 'sub-process-icon.svg',
  'user-action-icon': 'user-action-icon.svg',
  'error-icon': 'error-icon.svg',
  'soft-error-icon': 'soft-error-icon.svg',
  'table-icon': 'table-icon.svg',
} as const
