export const icons = {
  donut: '/donut.svg',
  circle: '/circle.svg',
  letter: '/letter.svg',
  'letter-thin': '/letter-thin.svg',
  diamond: '/diamond.svg',
  'diamond-black': '/diamond-black.svg',
  cross: '/cross.svg',
  gear: '/gear.svg',
  page: '/page.svg',
  loop: '/loop.svg',
  script: '/script.svg',
  triangle: '/triangle.svg',
  'triangle-white': '/triangle-white.svg',
  'sub-process': '/sub-process.svg',
  'user-action': '/user-action.svg',
} as const
