export const icons = {
  'connector-icon': 'connector-icon.svg',
  'end-icon': 'end-icon.svg',
  'gateway-icon': 'gateway-icon.svg',
  'error-icon': 'error-icon.svg',
  'in-progress-icon': 'in-progress-icon.svg',
  'loop-icon': 'loop-icon.svg',
  'message-inter-icon': 'message-inter-icon.svg',
  'message-icon': 'message-icon.svg',
  'not-started-icon': 'not-started-icon.svg',
  'frame-icon': 'frame-icon.svg',
  'parallel-icon': 'parallel-icon.svg',
  'script-icon': 'script-icon.svg',
  'service-call-icon': 'service-call-icon.svg',
  'signal-listen-icon': 'signal-listen-icon.svg',
  'signal-send-icon': 'signal-send-icon.svg',
  'soft-error-icon': 'soft-error-icon.svg',
  'start-icon': 'start-icon.svg',
  'table-icon': 'table-icon.svg',
  'test-done-icon': 'test-done-icon.svg',
  'timer-icon': 'timer-icon.svg',
  'user-action-icon': 'user-action-icon.svg',
  'custom-note-icon': 'custom-note-icon.svg',
  'subprocess-icon': 'subprocess-icon.svg',
  'dev-done-icon': 'dev-done-icon.svg',
  'database-icon': 'database-icon.svg',
} as const
