name: Azure Static Web Apps

pr:
  branches:
    include:
      - main
trigger:
  branches:
    include:
      - main

jobs:
  - job: build_and_deploy_job
    displayName: Build and Deploy Job
    condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: Azure-Static-Web-Apps-white-water-063486803-variable-group
    steps:
      - checkout: self
        submodules: true

      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'

      - script: |
          npm install -g pnpm
          pnpm install
          # Build client
          cd packages/editor/client
          pnpm build
          cd ../../..
          # Build server
          cd packages/editor/server
          pnpm build
          # Create staticwebapp.config.json if it doesn't exist
          if [ ! -f "staticwebapp.config.json" ]; then
            echo '{
              "platform": {
                "apiRuntime": "node:18"
              }
            }' > staticwebapp.config.json
          fi
        displayName: 'Install dependencies and build client/server'

      - task: AzureStaticWebApp@0
        displayName: 'Deploy to Azure Static Web Apps'
        inputs:
          azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_WATER_063486803)
          app_location: '/packages/editor/client'
          api_location: '/packages/editor/server'
          output_location: 'dist'
          api_language: 'nodejs'
          api_version: '18'
          skip_app_build: true
          skip_api_build: true
