import { Steps } from './540466_user_story_select_account.test'
export const steps: Steps = {
  enable: false,
  "Given A or B": async (state, value) => {debugger ;throw "Not implemented"},
  "Given Errors from demo": async (state, value) => {debugger ;throw "Not implemented"},
  "Then Message: Could not load page": async state => {debugger ;throw "Not implemented"},
  "Then Message: Display stuff": async state => {debugger ;throw "Not implemented"},
  "Then Script: Clear page": async state => {debugger ;throw "Not implemented"},
  "Then Script: Show something": async state => {debugger ;throw "Not implemented"},
  "Then Script: Some script": async state => {debugger ;throw "Not implemented"},
  "Then ServiceCall: api call demo": async state => {debugger ;throw "Not implemented"},
  "Then Subprocess: Saved payee Yet another subflow": async state => {debugger ;throw "Not implemented"},
  "Then Subprocess: Some subflow": async state => {debugger ;throw "Not implemented"},
  "Then Subprocess: Validate fields Payment data": async state => {debugger ;throw "Not implemented"},
  "Validate Gatuadress: Input field, RequiredString Format 135 characters, ": async () => {debugger ;throw "Not implemented"},
  "Validate Land: DropdownInputSelectDesktop, RequiredString Format 12 characters, Default value Sverige": async () => {debugger ;throw "Not implemented"},
  "Validate Mottagarens namn: Input field, RequiredString Format 135 characters, ": async () => {debugger ;throw "Not implemented"},
  "Validate Postnummer: Input field, Required String Format 135 characters, ": async () => {debugger ;throw "Not implemented"},
  "When Cancel": async state => {debugger ;throw "Not implemented"},
  "When Take action": async state => {debugger ;throw "Not implemented"},
}