import { Steps } from './some_feature.test'
export const steps: Steps = {
  enable: false,
  "Action: Cancel": async state => {debugger ;throw "Not implemented"},
  "Action: Take action": async state => {debugger ;throw "Not implemented"},
  "Given A or B": async (state, value) => {debugger ;throw "Not implemented"},
  "Given Errors from demo": async (state, value) => {debugger ;throw "Not implemented"},
  "Message: Could not load page": async state => {debugger ;throw "Not implemented"},
  "Message: Display stuff": async state => {debugger ;throw "Not implemented"},
  "Script: Clear page": async state => {debugger ;throw "Not implemented"},
  "Script: Do thing with thing": async state => {debugger ;throw "Not implemented"},
  "Script: Hide box": async state => {debugger ;throw "Not implemented"},
  "Script: Show box": async state => {debugger ;throw "Not implemented"},
  "ServiceCall: api call demo": async state => {debugger ;throw "Not implemented"},
  "SignalSend: Go back to registration page": async state => {debugger ;throw "Not implemented"},
  "Subprocess: Saved payee Yet another subflow": async state => {debugger ;throw "Not implemented"},
  "Subprocess: Some subflow": async state => {debugger ;throw "Not implemented"},
  "Subprocess: Validate fields Payment data": async state => {debugger ;throw "Not implemented"},
  "Validate Gatuadress: Input field, RequiredString Format 135 characters, ": async () => {debugger ;throw "Not implemented"},
  "Validate Land: DropdownInputSelectDesktop, RequiredString Format 12 characters, Default value Sverige": async () => {debugger ;throw "Not implemented"},
  "Validate Mottagarens namn: Input field, RequiredString Format 135 characters, ": async () => {debugger ;throw "Not implemented"},
  "Validate Postnummer: Input field, Required String Format 135 characters, ": async () => {debugger ;throw "Not implemented"},
}